# Настройка базы данных
storage:
  enable: false
  jdbcUrl: 'jdbc:mysql://localhost:3306/prison?useSSL=false'
  username: 'root'
  password: '123123'
  # Настройка пулов
  poolMax: 10

# Настройка режима
prison:
  # Настройка шахт
  mine:
    time: 1 # Время пополнения шахт

# Настройка сообщений
messages:
  money:
    no_money: 'У вас недостаточно денег'
  items:
    give: 'Вы получили %item%!'
  sell:
    sell_block: 'Вы продали блоки и получили %money%'
    sell_error: 'У вас нечего продавать'