# Настройка базы данных
storage:
  enable: false
  jdbcUrl: 'jdbc:mysql://localhost:3306/prison?useSSL=false'
  username: 'root'
  password: '123123'
  # Настройка пулов
  poolMax: 10

# Настройка режима
prison:
  # Настройка спавна
  spawn: world,7,72,7,-180,0
  # Настройка шахт
  mine:
    time: 1 # Время пополнения шахт

# Настройка чата
chat:
  radius: 50
  globalformat: "&eG &7[%group%&7] %player% &8[%prison_fraction%&8]&f: %message%"
  localformat: "&6L &7[%group%&7] %player% &8[%prison_fraction%&8]&f: %message%"

# Настройка сообщений
messages:
  money:
    no_money: 'У вас недостаточно денег'
  items:
    give: 'Вы получили %item%!'
  sell:
    sell_block: 'Вы продали блоки и получили %money%'
    sell_error: 'У вас нечего продавать'
  teleport: 'Вы были перемещены...'
  level_teleport: 'Вам не хватает уровня (Доступ от %level_required% уровня)'