# Настройка базы данных
storage:
  enable: false
  jdbcUrl: 'jdbc:mysql://localhost:3306/prison?useSSL=false'
  username: 'root'
  password: '123123'
  # Настройка пулов
  poolMax: 10

# Настройка сообщений